import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdirSync} from 'node:fs';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});
const page=await context.newPage(),errors=[];
page.on('pageerror',error=>errors.push(error.message));
const base=process.env.TEST_BASE_URL||'http://localhost:8000/';
async function search(text){await page.locator('#searchInput').fill(text);await page.locator('#searchForm').evaluate(form=>form.requestSubmit());await page.waitForTimeout(250);}
try{
 await page.goto(base);
 await page.waitForFunction(()=>document.querySelectorAll('.entry').length===30);
 assert(await page.locator('#homeView').isVisible());
 assert(await page.locator('#searchView').isHidden());
 assert.equal(await page.locator('#bankCount').textContent(),'1206 道');
 assert.equal(await page.locator('.bank-title').evaluate(el=>getComputedStyle(el).fontSize),'14px');
 assert.equal(await page.locator('.developer-logo').count(),2);
 assert(!(await page.locator('body').innerText()).includes('本程序由凯哥开发'));
 mkdirSync('dist',{recursive:true});
 await page.screenshot({path:'dist/home-mobile.png'});
 await page.locator('#openBank').click();
 assert(await page.locator('#searchView').isVisible());
 assert.equal(await page.locator('#header .brand').innerText(),'交安复习题');
 await page.locator('#more').click();
 assert.equal(await page.locator('.entry').count(),60);
 await search('上海莲花');
 assert.equal(await page.locator('[data-entry-id="DT00099"] .question').count(),4);
 await search('钱某');
 assert.equal(await page.locator('[data-entry-id="DT01121"] .question').count(),4);
 assert((await page.locator('[data-entry-id="DT01121"] mark').count())>1);
 const caseResults=await page.locator('.entry').count();
 assert.equal(await page.locator('#matchCount').textContent(),`1 / ${caseResults} 题`);
 await search('事故');
 const total=await page.locator('.entry').count();assert(total>2);
 const ids=await page.locator('.entry').evaluateAll(cards=>cards.map(c=>c.dataset.entryId));
 assert((await page.locator('mark').count())>total);
 assert.equal(await page.locator('#matchCount').textContent(),`1 / ${total} 题`);
 await page.locator('#nextMatch').click();
 assert.equal(await page.locator('#matchCount').textContent(),`2 / ${total} 题`);
 assert.equal(await page.locator('.active-entry').getAttribute('data-entry-id'),ids[1]);
 await page.locator('#prevMatch').click();
 assert.equal(await page.locator('#matchCount').textContent(),`1 / ${total} 题`);
 assert.equal(await page.locator('.active-entry').getAttribute('data-entry-id'),ids[0]);
 await page.locator('#nextMatch').click();await page.locator('#nextMatch').click();
 assert.equal(await page.locator('.active-entry').getAttribute('data-entry-id'),ids[2]);
 const position=await page.locator('.active-entry').evaluate(card=>({top:card.getBoundingClientRect().top,header:document.querySelector('header').getBoundingClientRect().bottom}));
 assert(position.top>=position.header,'question start must be below sticky header');
 await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));
 await search('赔偿责任');assert.equal(await page.evaluate(()=>scrollY),0);
 assert((await page.locator('#matchCount').textContent()).startsWith('1 / '));
 await search('lianhuahepan');assert(await page.locator('[data-entry-id="DT00099"]').count());
 const pinyinCount=await page.locator('.entry').count();
 assert.equal(await page.locator('#matchCount').textContent(),`1 / ${pinyinCount} 题`);
 assert.equal(await page.locator('#nextMatch').isDisabled(),pinyinCount<=1);
 await search('不存在xyz123456');assert.equal(await page.locator('.entry').count(),0);
 assert(await page.locator('#nextMatch').isDisabled());
 await search('');await page.locator('[data-type="案例题"]').click();
 await page.locator('#more').click();assert.equal(await page.locator('.entry').count(),40);
 await page.locator('[data-type="知识卡"]').click();assert.equal(await page.locator('.entry').count(),26);
 await page.locator('[data-type="全部"]').click();await search('赵某与钱某');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile horizontal overflow');
 assert.equal(await page.locator('details, #showAnswers, .source-section, .entry-head').count(),0);
 assert.equal(await page.locator('.answer:visible').count(),4);
 assert.deepEqual(await page.locator('#typeFilters button').allTextContents(),['全部','单选','多选','判断','案例题','知识卡']);
 assert(!(await page.locator('#list').innerText()).includes('原题号'));
 mkdirSync('dist',{recursive:true});
 await page.screenshot({path:'dist/reading-mobile.png',fullPage:true});
 await page.setViewportSize({width:1280,height:900});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.evaluate(()=>navigator.serviceWorker.ready);
 await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
 await context.setOffline(true);await page.reload();
 await page.waitForFunction(()=>document.querySelectorAll('.entry').length===30);
 await search('赵某与钱某');assert.equal(await page.locator('[data-entry-id="DT01121"] .question').count(),4);
 await page.locator('.back-home').click();
 await page.locator('#homeView').waitFor({state:'visible'});
 assert(await page.locator('#homeView').isVisible());
 assert(await page.locator('#recentStudy').isVisible());
 assert(await page.locator('#matchNav').isHidden());
 await page.goBack();
 await page.locator('#searchView').waitFor({state:'visible'});
 assert(await page.locator('#searchView').isVisible());
 assert.equal(await page.locator('#searchInput').inputValue(),'赵某与钱某');
 assert.equal(await page.locator('#searchView').evaluate(el=>getComputedStyle(el).animationName),'none');
 const motionContext=await browser.newContext({viewport:{width:390,height:844}});
 const motionPage=await motionContext.newPage();
 await motionPage.goto(base);
 await motionPage.locator('#homeView').waitFor({state:'visible'});
 assert.equal(await motionPage.locator('#homeView').evaluate(el=>getComputedStyle(el).animationName),'viewIn');
 await motionPage.locator('#openBank').click();
 assert.equal(await motionPage.locator('#searchView').evaluate(el=>getComputedStyle(el).animationName),'viewIn');
 await motionPage.screenshot({path:'dist/home-motion-mobile.png'});
 await motionContext.close();
 assert.deepEqual(errors,[]);
 console.log('PASS: mobile/desktop rendering, complete cases, navigation, reset, filters, offline reload, no JS errors');
}finally{await browser.close();}
