import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdirSync} from 'node:fs';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});
const page=await context.newPage(),errors=[];
page.on('pageerror',error=>errors.push(error.message));
const base=process.env.TEST_BASE_URL||'http://localhost:8000/';
async function search(text){await page.locator('#searchInput').fill(text);await page.locator('#searchForm').evaluate(form=>form.requestSubmit());await page.waitForTimeout(250);}
try{
 await page.goto(base);
 await page.waitForFunction(()=>document.querySelectorAll('.entry').length===30);
 await page.locator('#more').click();
 assert.equal(await page.locator('.entry').count(),60);
 await search('上海莲花');
 assert.equal(await page.locator('[data-entry-id="DT00099"] .question').count(),4);
 await search('钱某');
 assert.equal(await page.locator('[data-entry-id="DT01121"] .question').count(),4);
 const total=await page.locator('mark').count();assert(total>2);
 assert.equal(await page.locator('#matchCount').textContent(),`1 / ${total}`);
 await page.locator('#nextMatch').click();
 assert.equal(await page.locator('#matchCount').textContent(),`2 / ${total}`);
 await page.locator('#prevMatch').click();
 assert.equal(await page.locator('#matchCount').textContent(),`1 / ${total}`);
 await page.locator('#nextMatch').click();await page.locator('#nextMatch').click();
 const position=await page.locator('.active-match').evaluate(mark=>({top:mark.getBoundingClientRect().top,header:document.querySelector('header').getBoundingClientRect().bottom}));
 assert(position.top>=position.header,'keyword must be below sticky header');
 await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));
 await search('赔偿责任');assert.equal(await page.evaluate(()=>scrollY),0);
 await search('lianhuahepan');assert(await page.locator('[data-entry-id="DT00099"]').count());
 assert(await page.locator('#nextMatch').isDisabled());
 await search('不存在xyz123456');assert.equal(await page.locator('.entry').count(),0);
 assert(await page.locator('#nextMatch').isDisabled());
 await search('');await page.locator('[data-type="知识卡"]').click();assert.equal(await page.locator('.entry').count(),23);
 await page.locator('[data-type="全部"]').click();await search('赵某与钱某');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile horizontal overflow');
 await page.locator('#showAnswers').uncheck();
 assert.equal(await page.locator('.answer[open]').count(),0);
 await page.locator('#showAnswers').check();
 mkdirSync('dist',{recursive:true});
 await page.screenshot({path:'dist/reading-mobile.png',fullPage:true});
 await page.setViewportSize({width:1280,height:900});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.evaluate(()=>navigator.serviceWorker.ready);
 await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
 await context.setOffline(true);await page.reload();
 await page.waitForFunction(()=>document.querySelectorAll('.entry').length===30);
 await search('赵某与钱某');assert.equal(await page.locator('[data-entry-id="DT01121"] .question').count(),4);
 assert.deepEqual(errors,[]);
 console.log('PASS: mobile/desktop rendering, complete cases, navigation, reset, filters, offline reload, no JS errors');
}finally{await browser.close();}
